"""share_files + multi-share fields

Revision ID: d89c0a886a7e
Revises: d369a263a54e
Create Date: 2026-05-12 02:50:45.256818

"""
from __future__ import annotations

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'd89c0a886a7e'
down_revision: str | None = 'd369a263a54e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('share_files',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('share_id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('prefix', sa.String(length=255), nullable=True),
    sa.Column('suffix', sa.String(length=32), nullable=True),
    sa.Column('size', sa.BigInteger(), nullable=False),
    sa.Column('file_path', sa.String(length=1024), nullable=False),
    sa.Column('file_hash', sa.String(length=128), nullable=True),
    sa.Column('content_type', sa.String(length=255), nullable=True),
    sa.Column('upload_id', sa.String(length=255), nullable=True),
    sa.Column('is_chunked', sa.Boolean(), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['share_id'], ['filecodes.id'], name=op.f('fk_share_files_share_id_filecodes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_share_files'))
    )
    with op.batch_alter_table('share_files', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_share_files_share_id'), ['share_id'], unique=False)
        batch_op.create_index('ix_share_files_share_order', ['share_id', 'order'], unique=False)

    with op.batch_alter_table('filecodes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kind', sa.String(length=16), server_default='file', nullable=False))
        batch_op.add_column(sa.Column('total_size', sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column('file_count', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('finalized', sa.Boolean(), server_default='1', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('filecodes', schema=None) as batch_op:
        batch_op.drop_column('finalized')
        batch_op.drop_column('file_count')
        batch_op.drop_column('total_size')
        batch_op.drop_column('kind')

    with op.batch_alter_table('share_files', schema=None) as batch_op:
        batch_op.drop_index('ix_share_files_share_order')
        batch_op.drop_index(batch_op.f('ix_share_files_share_id'))

    op.drop_table('share_files')
    # ### end Alembic commands ###
