"""initial schema

Revision ID: d369a263a54e
Revises:
Create Date: 2026-05-12 01:09:31.050719

"""
from __future__ import annotations

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'd369a263a54e'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('action', sa.Enum('SHARE_CREATE', 'SHARE_RETRIEVE', 'ADMIN_ACTION', name='accesslogaction', native_enum=False, length=32), nullable=False),
    sa.Column('code', sa.String(length=16), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('ua', sa.String(length=512), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_access_logs'))
    )
    with op.batch_alter_table('access_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_access_logs_action'), ['action'], unique=False)
        batch_op.create_index('ix_access_logs_action_ts', ['action', 'ts'], unique=False)
        batch_op.create_index(batch_op.f('ix_access_logs_code'), ['code'], unique=False)
        batch_op.create_index(batch_op.f('ix_access_logs_ip'), ['ip'], unique=False)
        batch_op.create_index(batch_op.f('ix_access_logs_ts'), ['ts'], unique=False)

    op.create_table('filecodes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('prefix', sa.String(length=255), nullable=True),
    sa.Column('suffix', sa.String(length=32), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('size', sa.BigInteger(), nullable=True),
    sa.Column('file_path', sa.String(length=1024), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('file_hash', sa.String(length=128), nullable=True),
    sa.Column('expired_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expired_count', sa.Integer(), nullable=False),
    sa.Column('used_count', sa.Integer(), nullable=False),
    sa.Column('is_chunked', sa.Boolean(), nullable=False),
    sa.Column('upload_id', sa.String(length=255), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_ip', sa.String(length=64), nullable=True),
    sa.Column('created_by_ua', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_filecodes'))
    )
    with op.batch_alter_table('filecodes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_filecodes_code'), ['code'], unique=True)
        batch_op.create_index('ix_filecodes_code_active', ['code', 'deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_filecodes_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_filecodes_expired_at'), ['expired_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_filecodes_file_hash'), ['file_hash'], unique=False)

    op.create_table('multipart_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('upload_id', sa.String(length=64), nullable=False),
    sa.Column('key', sa.String(length=1024), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('content_type', sa.String(length=255), nullable=True),
    sa.Column('parts_total', sa.Integer(), nullable=False),
    sa.Column('parts_uploaded', sa.JSON(), nullable=True),
    sa.Column('s3_upload_id', sa.String(length=255), nullable=False),
    sa.Column('expire_value', sa.Integer(), nullable=False),
    sa.Column('expire_style', sa.String(length=16), nullable=False),
    sa.Column('created_by_ip', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_multipart_sessions'))
    )
    with op.batch_alter_table('multipart_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_multipart_sessions_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_multipart_sessions_upload_id'), ['upload_id'], unique=True)

    op.create_table('settings_kv',
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('value', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_settings_kv'))
    )
    op.create_table('upload_chunks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('upload_id', sa.String(length=64), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('chunk_path', sa.String(length=1024), nullable=False),
    sa.Column('chunk_size', sa.BigInteger(), nullable=False),
    sa.Column('hash', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_upload_chunks')),
    sa.UniqueConstraint('upload_id', 'chunk_index', name='uq_upload_chunks_upload_id_chunk_index')
    )
    with op.batch_alter_table('upload_chunks', schema=None) as batch_op:
        batch_op.create_index('ix_upload_chunks_created_at', ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_upload_chunks_upload_id'), ['upload_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('upload_chunks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_upload_chunks_upload_id'))
        batch_op.drop_index('ix_upload_chunks_created_at')

    op.drop_table('upload_chunks')
    op.drop_table('settings_kv')
    with op.batch_alter_table('multipart_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_multipart_sessions_upload_id'))
        batch_op.drop_index(batch_op.f('ix_multipart_sessions_expires_at'))

    op.drop_table('multipart_sessions')
    with op.batch_alter_table('filecodes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_filecodes_file_hash'))
        batch_op.drop_index(batch_op.f('ix_filecodes_expired_at'))
        batch_op.drop_index(batch_op.f('ix_filecodes_deleted_at'))
        batch_op.drop_index('ix_filecodes_code_active')
        batch_op.drop_index(batch_op.f('ix_filecodes_code'))

    op.drop_table('filecodes')
    with op.batch_alter_table('access_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_access_logs_ts'))
        batch_op.drop_index(batch_op.f('ix_access_logs_ip'))
        batch_op.drop_index(batch_op.f('ix_access_logs_code'))
        batch_op.drop_index('ix_access_logs_action_ts')
        batch_op.drop_index(batch_op.f('ix_access_logs_action'))

    op.drop_table('access_logs')
    # ### end Alembic commands ###
