import type { ShareMultiFile, ShareSelectResponse } from '@/lib/api/share';
import { Icon } from './IconSprite';

export function PickupDetail({item,onClose}:{item:ShareSelectResponse;onClose:()=>void}) {
  const files:ShareMultiFile[]=item.kind==='multi'?(item.files||[]):item.kind==='file'?[{file_id:0,order:0,name:item.name||item.code,size:item.size||0,url:item.url,content_type:item.content_type,force_download:item.force_download}]:[];
  const meta=item.kind==='text'?`${new Blob([item.text||'']).size} B · 文字`:item.kind==='multi'?`${item.file_count||files.length} 个文件 · ${fmt(item.total_size||0)}`:`${fmt(item.size||0)} · ${item.content_type||'文件'}`;
  const copy=(s:string)=>void navigator.clipboard?.writeText(s).catch(()=>{});
  const downloadAll=()=>{files.forEach((f,i)=>{if(!f.url)return;window.setTimeout(()=>window.open(f.url!,'_blank','noopener'),i*120)});};
  return <div data-yd="backdrop" data-r="backdrop" onClick={onClose} style={backdrop}>
    <div data-yd="dialog" data-r="sheet" onClick={e=>e.stopPropagation()} style={sheet}>
      <div data-r="grabber" style={{display:'none',padding:'10px 0 4px'}}><div style={{width:36,height:5,borderRadius:999,background:'var(--grab)',margin:'0 auto'}}/></div>
      <div style={{display:'flex',alignItems:'flex-start',gap:12,padding:'18px 20px 14px',borderBottom:'1px solid var(--ln)'}}><div style={{flex:1,minWidth:0}}><div style={{fontSize:18,fontWeight:700,letterSpacing:'-.01em',color:'var(--tx)',overflow:'hidden',textOverflow:'ellipsis',whiteSpace:'nowrap'}}>{item.name|| (item.kind==='text'?'文字分享':item.code)}</div><div style={{fontSize:12,color:'var(--tx3)',marginTop:3}}>{meta}</div></div><button type="button" data-yd="icon-btn" onClick={onClose} style={close}><Icon name="i-x" size={15}/></button></div>
      <div style={{padding:'16px 20px 20px'}}>
        <Preview item={item}/>
        {files.length>0&&<div style={{marginTop:14,border:'1px solid var(--ln)',borderRadius:12,overflow:'hidden'}}>{files.map((f,i)=><a key={f.file_id||i} href={f.url||'#'} target="_blank" rel="noopener noreferrer" style={{display:'flex',alignItems:'center',gap:10,padding:'11px 14px',borderTop:i?'1px solid var(--ln)':'none',fontSize:14,color:'var(--tx1)'}}><Icon name={iconFor(f.content_type)} size={16} style={{color:'var(--tx3)',flexShrink:0}}/><span style={{flex:1,minWidth:0,overflow:'hidden',textOverflow:'ellipsis',whiteSpace:'nowrap'}}>{f.name}</span><span style={{fontFamily:"'JetBrains Mono',monospace",fontSize:12,color:'var(--tx3)'}}>{fmt(f.size)}</span><Icon name="i-dl" size={16} style={{color:'var(--act)',flexShrink:0}}/></a>)}</div>}
        <div style={{display:'flex',gap:8,marginTop:16,flexWrap:'wrap'}}>{files.length>0&&<button type="button" data-yd="btn" onClick={downloadAll} style={primary}><Icon name="i-dl" size={16}/>下载全部</button>}<button type="button" data-yd="quiet" onClick={()=>copy(item.code)} style={quiet}><Icon name="i-copy" size={15}/>复制取件码</button><button type="button" data-yd="quiet" onClick={()=>copy(`${location.origin}/s/${item.code}`)} style={quiet}><Icon name="i-link" size={15}/>分享链接</button></div>
      </div>
    </div>
  </div>;
}
function Preview({item}:{item:ShareSelectResponse}){if(item.kind==='text')return <pre style={{minHeight:170,maxHeight:360,overflow:'auto',margin:0,borderRadius:12,background:'var(--p1)',border:'1px solid var(--ln)',padding:14,whiteSpace:'pre-wrap',fontFamily:'inherit',fontSize:13,lineHeight:1.65,color:'var(--tx1)'}}>{item.text}</pre>;const url=item.url;const ct=item.content_type||'';if(url&&ct.startsWith('image/'))return <img src={url} alt={item.name||'预览'} style={media}/>;if(url&&ct.startsWith('video/'))return <video controls src={url} style={media}/>;if(url&&ct.startsWith('audio/'))return <div style={placeholder}><audio controls src={url} style={{width:'90%'}}/></div>;if(url&&ct==='application/pdf')return <iframe src={url} title={item.name||'PDF'} style={{...media,height:320}}/>;return <div style={placeholder}><Icon name={iconFor(ct)} size={26}/><span style={{fontSize:13}}>{item.kind==='multi'?'多文件分享':ct||'文件可下载'}</span></div>;}
function iconFor(ct:string|null){return ct?.startsWith('image/')?'i-img':ct?.startsWith('video/')?'i-vid':ct?.startsWith('audio/')?'i-file':'i-file';}
function fmt(n:number){if(n<1024)return`${n} B`;if(n<1024**2)return`${(n/1024).toFixed(1)} KB`;if(n<1024**3)return`${(n/1024**2).toFixed(1)} MB`;return`${(n/1024**3).toFixed(1)} GB`;}
const backdrop:React.CSSProperties={position:'fixed',inset:0,zIndex:60,background:'rgba(4,6,10,.55)',display:'flex',alignItems:'center',justifyContent:'center',padding:24};const sheet:React.CSSProperties={width:520,maxWidth:'100%',maxHeight:'86vh',overflow:'auto',background:'var(--pn)',border:'1px solid var(--ln)',borderRadius:16,boxShadow:'var(--shl)'};const close:React.CSSProperties={width:30,height:30,borderRadius:8,border:'1px solid var(--ln)',display:'flex',alignItems:'center',justifyContent:'center',color:'var(--tx2)',cursor:'pointer',flexShrink:0,background:'transparent'};const placeholder:React.CSSProperties={height:170,borderRadius:12,background:'var(--p1)',border:'1px solid var(--ln)',display:'flex',flexDirection:'column',alignItems:'center',justifyContent:'center',gap:8,color:'var(--tx3)'};const media:React.CSSProperties={width:'100%',maxHeight:360,objectFit:'contain',borderRadius:12,background:'var(--p1)',border:'1px solid var(--ln)'};const primary:React.CSSProperties={flex:1,minWidth:150,height:46,border:0,borderRadius:10,background:'var(--ac)',color:'#fff',fontFamily:'inherit',fontSize:15,fontWeight:600,cursor:'pointer',display:'inline-flex',alignItems:'center',justifyContent:'center',gap:8};const quiet:React.CSSProperties={height:46,padding:'0 16px',border:'1px solid var(--ln2)',borderRadius:10,background:'transparent',color:'var(--tx1)',fontFamily:'inherit',fontSize:14,cursor:'pointer',display:'inline-flex',alignItems:'center',gap:7};
